#!/usr/bin/env python3
"""
バックテスト結果 (strategy_results_*.json) から GA最適化重みを読み込み、
lib/backtestWeights.ts を自動生成する。
GitHub Actions の commit-results ジョブから呼ばれる。
"""
import json, os, sys
from pathlib import Path

REPO = Path(__file__).parent.parent
SWING_JSON = REPO / "backtest" / "strategy_results_swing.json"
DAY_JSON   = REPO / "backtest" / "strategy_results_day.json"
OUT_FILE   = REPO / "lib" / "backtestWeights.ts"

def normalize(weights: dict, target_sum: float = 4.0) -> dict:
    s = sum(weights.values())
    if s < 1e-10:
        return weights
    scale = target_sum / s
    return {k: round(v * scale, 4) for k, v in weights.items()}

def load_result(path: Path):
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)

def main():
    swing = load_result(SWING_JSON)
    day   = load_result(DAY_JSON)

    if swing is None and day is None:
        print("ERROR: No backtest results found", file=sys.stderr)
        sys.exit(1)

    lines = [
        "// AUTO-GENERATED by backtest/update_scorer.py — do not edit manually",
    ]

    # ── SWING ─────────────────────────────────────────────────────────────────
    if swing:
        w_raw = swing["summary"]["best_weights"]
        w_norm = normalize(w_raw)
        wf = swing.get("walk_forward", {})
        meta = {
            "generatedAt": swing.get("generated_at", ""),
            "bestSharpe": swing.get("summary", {}).get("best_sharpe", 0),
            "avgOosSharpe": wf.get("avg_oos_sharpe", 0),
            "bestSellRule": swing.get("summary", {}).get("best_sell_rule", ""),
            "version": swing.get("version", 0),
        }
        lines.append("")
        lines.append(f"// swing v{meta['version']}: {meta['generatedAt']}")
        lines.append("export const SWING_WEIGHTS: Record<string, number> = {")
        for k, v in w_norm.items():
            lines.append(f"  {k}: {v},")
        lines.append("};")
        lines.append("")
        lines.append("export const SWING_META = {")
        lines.append(f"  generatedAt: {json.dumps(meta['generatedAt'])},")
        lines.append(f"  bestSharpe: {meta['bestSharpe']},")
        lines.append(f"  avgOosSharpe: {meta['avgOosSharpe']},")
        lines.append(f"  bestSellRule: {json.dumps(meta['bestSellRule'])},")
        lines.append(f"  version: {meta['version']},")
        lines.append("};")
    else:
        # Keep existing values if swing not available
        lines.append("")
        lines.append("// swing: no results available — keeping previous weights")
        lines.append("export const SWING_WEIGHTS: Record<string, number> = {")
        lines.append("  RSI: 0.6836, MACD: 0.4358, BB: 0.4334, MA: 0.0054,")
        lines.append("  Aroon: 0.5583, Stoch: 0.1480, CCI: 0.2831, ROC: 1.4521,")
        lines.append("};")
        lines.append("export const SWING_META = { generatedAt: '', bestSharpe: 0, avgOosSharpe: 0, bestSellRule: '', version: 0 };")

    # ── DAY ───────────────────────────────────────────────────────────────────
    if day:
        w_raw_day = day["summary"]["best_weights"]
        # Exclude VWAP (not computable from daily bars)
        w_no_vwap = {k: v for k, v in w_raw_day.items() if k != "VWAP"}
        w_norm_day = normalize(w_no_vwap)
        wf_day = day.get("walk_forward", {})
        meta_day = {
            "generatedAt": day.get("generated_at", ""),
            "bestSharpe": day.get("summary", {}).get("best_sharpe", 0),
            "avgOosSharpe": wf_day.get("avg_oos_sharpe", 0),
            "bestSellRule": day.get("summary", {}).get("best_sell_rule", ""),
            "version": day.get("version", 0),
        }
        lines.append("")
        lines.append(f"// day v{meta_day['version']}: {meta_day['generatedAt']}  (VWAP excluded — not computable from daily bars)")
        lines.append("export const DAY_WEIGHTS: Record<string, number> = {")
        for k, v in w_norm_day.items():
            lines.append(f"  {k}: {v},")
        lines.append("};")
        lines.append("")
        lines.append("export const DAY_META = {")
        lines.append(f"  generatedAt: {json.dumps(meta_day['generatedAt'])},")
        lines.append(f"  bestSharpe: {meta_day['bestSharpe']},")
        lines.append(f"  avgOosSharpe: {meta_day['avgOosSharpe']},")
        lines.append(f"  bestSellRule: {json.dumps(meta_day['bestSellRule'])},")
        lines.append(f"  version: {meta_day['version']},")
        lines.append("};")
    else:
        lines.append("")
        lines.append("// day: no results available — keeping previous weights")
        lines.append("export const DAY_WEIGHTS: Record<string, number> = {")
        lines.append("  RSI: 0.7299, MACD: 0.4254, BB: 1.5178, MA: 0.0557,")
        lines.append("  Stoch: 1.1562, ROC: 0.1017, CCI: 0.0135,")
        lines.append("};")
        lines.append("export const DAY_META = { generatedAt: '', bestSharpe: 0, avgOosSharpe: 0, bestSellRule: '', version: 0 };")

    content = "\n".join(lines) + "\n"
    OUT_FILE.write_text(content)
    print(f"✓ {OUT_FILE} を更新しました")
    if swing:
        print(f"  swing: bestSharpe={swing['summary']['best_sharpe']}, sellRule={swing['summary']['best_sell_rule']}")
    if day:
        print(f"  day: bestSharpe={day['summary']['best_sharpe']}, sellRule={day['summary']['best_sell_rule']}")

if __name__ == "__main__":
    main()
