// AUTO-GENERATED by backtest/update_scorer.py — do not edit manually

// swing v15: 2026-06-04 13:27
export const SWING_WEIGHTS: Record<string, number> = {
  RSI: 0.4397,
  MACD: 0.9245,
  BB: 0.0148,
  EMA200: 0.6559,
  MOM3M: 0.6266,
  Stoch: 0.0,
  CCI: 0.5049,
  52WK: 0.8335,
};

export const SWING_META = {
  generatedAt: "2026-06-04 13:27",
  bestSharpe: 47.0052,
  avgOosSharpe: -0.3182,
  bestSellRule: "target10_stop5",
  version: 15,
};

// day v15: 2026-06-04 13:44  (VWAP excluded — not computable from daily bars)
export const DAY_WEIGHTS: Record<string, number> = {
  RSI: 0.0,
  MACD: 0.2352,
  BB: 0.2257,
  MA: 0.131,
  RVOL: 1.8513,
  VWAP_B: 0.0,
  ORB: 1.3899,
  MOM3B: 0.1669,
};

export const DAY_META = {
  generatedAt: "2026-06-04 13:44",
  bestSharpe: 35.4845,
  avgOosSharpe: -4.1725,
  bestSellRule: "hold_2b",
  version: 15,
};
