// AUTO-GENERATED by backtest/update_scorer.py — do not edit manually

// swing v15: 2026-06-04 10:54
export const SWING_WEIGHTS: Record<string, number> = {
  RSI: 0.5112,
  MACD: 0.9034,
  BB: 0.0026,
  EMA200: 0.6467,
  MOM3M: 0.6446,
  Stoch: 0.0021,
  CCI: 0.4824,
  52WK: 0.807,
};

export const SWING_META = {
  generatedAt: "2026-06-04 10:54",
  bestSharpe: 47.0351,
  avgOosSharpe: 0.1994,
  bestSellRule: "target10_stop5",
  version: 15,
};

// day v15: 2026-06-04 11:53  (VWAP excluded — not computable from daily bars)
export const DAY_WEIGHTS: Record<string, number> = {
  RSI: 0.0405,
  MACD: 0.0787,
  BB: 0.388,
  MA: 0.5445,
  RVOL: 1.1885,
  VWAP_B: 0.0539,
  ORB: 0.0281,
  MOM3B: 1.6778,
};

export const DAY_META = {
  generatedAt: "2026-06-04 11:53",
  bestSharpe: 47.3182,
  avgOosSharpe: 10.7914,
  bestSellRule: "hold_2b",
  version: 15,
};
