// AUTO-GENERATED by backtest/update_scorer.py — do not edit manually

// swing v11: 2026-06-02 02:55
export const SWING_WEIGHTS: Record<string, number> = {
  RSI: 0.0,
  MACD: 0.0,
  BB: 1.8342,
  EMA200: 0.0,
  MOM3M: 1.1554,
  Stoch: 0.0,
  CCI: 0.0,
  52WK: 1.0103,
};

export const SWING_META = {
  generatedAt: "2026-06-02 02:55",
  bestSharpe: 0.2855,
  avgOosSharpe: 0.1731,
  bestSellRule: "target20_stop7",
  version: 11,
};

// day v11: 2026-06-02 06:49  (VWAP excluded — not computable from daily bars)
export const DAY_WEIGHTS: Record<string, number> = {
  RSI: 0.2673,
  MACD: 0.5335,
  BB: 0.367,
  MA: 1.8236,
  Stoch: 0.2282,
  RVOL: 0.4222,
  CCI: 0.3582,
};

export const DAY_META = {
  generatedAt: "2026-06-02 06:49",
  bestSharpe: 37.6064,
  avgOosSharpe: 10.0958,
  bestSellRule: "target3_stop2",
  version: 11,
};
